jsdom/whatwg-url

lib/url.js
Wasn't sure exactly your preferred method for resolving this so I did a PR
=> Fix lint errors

README.md, lib/URL-impl.js, package.json, scripts/get-latest-platform-tests.js, src/url-state-machine.js, test/web-platform.js
=> Add setter tests and fix setter and constructor failure behavior

scripts/get-latest-platform-tests.js, src/url-state-machine.js
Follows https://github.com/whatwg/url/pull/185.
Don't merge until the WPTs have landed in master, then change the commit hash.
=> Spec update: add opaque hosts

README.md, scripts/get-latest-platform-tests.js, src/url-state-machine.js
Follows https://github.com/whatwg/url/pull/218.
=> Spec update: allow percent-encoding in non-special URLs' hosts

README.md, scripts/get-latest-platform-tests.js, src/url-state-machine.js
Follows https://github.com/whatwg/url/pull/240.
=> Spec update: Use Nontransitional_Processing for IDNA ToASCII

README.md, lib/URL-impl.js, scripts/get-latest-platform-tests.js
Follows https://github.com/whatwg/url/pull/254.
=> Spec update: remove javascript URL special case in the hash setter

README.md, scripts/get-latest-platform-tests.js, src/url-state-machine.js
Follows https://github.com/whatwg/url/pull/269.
=> Spec update: restrict the protocol setter for "file"

src/url-state-machine.js
This does not change the output at all.
=> Spec update: use a different algorithm for IPv6 serialization

README.md, scripts/get-latest-platform-tests.js, src/url-state-machine.js
Follows https://github.com/whatwg/url/pull/278.
=> Spec update: trim leading slashes of file URL paths

README.md, scripts/get-latest-platform-tests.js, src/url-state-machine.js
=> Spec update: fix windows drive letter handling in the file state

.eslintignore, .gitignore, README.md, lib/URL-impl.js, lib/URLSearchParams-impl.js, lib/infra.js, lib/public-api.js, package-lock.json, package.json, scripts/get-latest-platform-tests.js, scripts/transform.js, src/URL.idl, src/URLSearchParams.idl, src/url-state-machine.js, src/urlencoded.js, test/testharness.js, test/web-platform.js
This is currently blocked on webidl2js changes:
With those two changes merged, and the following TODOs done, this PR should be ready for merging. Before then, code review is welcome.
Fixes: https://github.com/jsdom/whatwg-url/issues/37
=> WIP: add support for URLSearchParams

README.md, lib/URLSearchParams-impl.js, package-lock.json, package.json, scripts/get-latest-platform-tests.js, test/web-platform.js
Will be helpful in #100.
Fixes #97.
=> Use new domexception module

README.md, scripts/get-latest-platform-tests.js, src/url-state-machine.js
Follows https://github.com/whatwg/url/pull/343.
Tests https://github.com/w3c/web-platform-tests/pull/7326.
=> Spec update: Windows drive letter quirk in the file slash state

.gitignore, README.md, scripts/get-latest-platform-tests.js, src/url-state-machine.js
Follows https://github.com/whatwg/url/pull/347.
----
Before it can merge, need to get https://github.com/w3c/web-platform-tests/pull/7641 fixed and merged, and also remember to update the readme.
=> Spec update: percent-encode more in fragments

README.md
It took me quite awhile (especially being unfamiliar with NPM) to figure out how to run tests and live viewer. I thought I'd just put some instructions in the README file.
=> Added setup instructions to README.md.

lib/URL-impl.js
=> Change invalid URL error messages to include the input

package.json, scripts/get-latest-platform-tests.js, test/web-platform.js
* Move away from RawGit as it's gone
* Move to new .any.js files instead of .html files
* Use got instead of request since it's a bit lighter
=> Update web platform tests infrastructure

package.json
This is advised by newer versions of npm.
Will merge assuming CI is happy.
=> Use "prepare" script instead of "prepublish"

scripts/get-latest-platform-tests.js, test/testharness.js
=> Roll web platform tests to latest

src/url-state-machine.js
It seems to do more than is required.
=> Simplify findLongestZeroSequence a bit

README.md, src/url-state-machine.js
See https://github.com/whatwg/url/pull/509.
=> Refactor "parse relative"

README.md, scripts/get-latest-platform-tests.js, src/url-state-machine.js
Follows https://github.com/whatwg/url/pull/459.
Will need to update README commit pointer and the web platform tests commit hash before this can be merged.
=> Spec update: forbid <, >, and ^ in hosts

README.md, scripts/get-latest-platform-tests.js, src/url-state-machine.js
See https://github.com/whatwg/url/pull/505.
=> Non-special URLs were not idempotent

README.md, scripts/get-latest-platform-tests.js, src/url-state-machine.js
Follows https://github.com/whatwg/url/pull/550.
Will merge if CI passes.
=> Spec update: fix file: URL reparse issue

scripts/get-latest-platform-tests.js, test/web-platform.js
Follows https://github.com/web-platform-tests/wpt/pull/26317.
Do not merge until that gets merged and we can update the tests commit SHA.
=> Incorporate the latest web platform percent-encoding tests

README.md, scripts/get-latest-platform-tests.js, src/url-state-machine.js
Follows https://github.com/whatwg/url/pull/589.
=> Disallow | in hosts

scripts/get-latest-platform-tests.js, src/url-state-machine.js
Align with https://github.com/whatwg/url/pull/604. Tests are in https://github.com/web-platform-tests/wpt/pull/29021
=> Make hostname setter return failure if a port is given

README.md, package-lock.json, package.json, scripts/get-latest-platform-tests.js
=> Update WPT, spec SHA, and dependencies

README.md, scripts/get-latest-platform-tests.js, src/url-state-machine.js
See https://github.com/whatwg/url/pull/582
=> Ensure path-only URLs cannot have their paths erased by the pathname setter

README.md, scripts/get-latest-platform-tests.js, src/url-state-machine.js
Follows https://github.com/whatwg/url/pull/619.
Do not merge until the spec and tests PRs are merged and we can update the README and get-latest-platform-tests script.
=> Reject non-IPv4 hostnames that end in numbers

LICENSE.txt, live-viewer/index.html, package-lock.json, package.json
Getting the easy stuff out of the way before doing the webidl2js update...
=> Repo updates

README.md, lib/url-state-machine.js, scripts/get-latest-platform-tests.js
See https://github.com/whatwg/url/pull/685
Passes https://github.com/web-platform-tests/wpt/pull/32524
=> Split forbidden host/domain code-points

README.md, scripts/get-latest-platform-tests.js
=> Update specification and test commit SHAs

README.md, lib/URL-impl.js, lib/URLSearchParams-impl.js, scripts/get-latest-platform-tests.js
/cc @annevk to check this against https://github.com/whatwg/url/pull/728 and see the test failures.
=> Draft of whatwg/url 728

README.md, lib/url-state-machine.js, scripts/get-latest-platform-tests.js
Follows https://github.com/whatwg/url/commit/eee49fdf4f99d59f717cbeb0bce29fda930196d4.
=> Change blob: URL origin serialization for inner non-http(s): URL

README.md
If that URL looks correct, I will also submit a PR to `@types/whatwg-url`
=> docs: update specification link for percentDecodeString()

README.md, lib/url-state-machine.js
=> Incorporate editorial updates

lib/percent-encoding.js, scripts/get-latest-platform-tests.js
Follows https://github.com/whatwg/url/commit/9bc33c39d4a6cd6a936ea7620b5a69f606ec0d4c.
=> Add U+005E (^) to the path percent-encode set
