test/web-platform.js
This helps ensure that passing in a URL object instead of a string to the 2nd argument of the constructor works as expected.
Related issue: https://github.com/whatwg/url/issues/80
=> Add MDN examples to tests.

README.md, scripts/get-latest-platform-tests.js, src/url-state-machine.js
It turns out d1dc30674f208a8c2ab54ac1c4dd91848d4b1078 was incomplete and didn't account for the spec's lowercase comparison. Raised by https://github.com/w3c/web-platform-tests/pull/2569.
=> Make %2E as well as %2e be turned into .

src/url-state-machine.js, test/to-upstream.json
Windows file URLs seem to have regressed between whatwg-url 3.1.0 and 4.1.0, at least according to jsdom test results. Very strangely no such tests are included upstream.
=> File URLs test

README.md, lib/URL-impl.js, scripts/get-latest-platform-tests.js, src/url-state-machine.js
This aligns with https://github.com/whatwg/url/pull/186.
/cc @annevk. As mentioned in https://github.com/w3c/web-platform-tests/pull/4405#issuecomment-269654674 one test is failing with this change, so something's not right---either in the tests, in the translation of the spec PR into code, or in the spec.
We should not merge this until the WPT PR is merged, and then we should update the commit hash to point to WPT master.
=> Spec update: get rid of null passwords

README.md, scripts/get-latest-platform-tests.js, src/url-state-machine.js
This follows https://github.com/whatwg/url/pull/156.
/cc @annevk. As noted in https://github.com/w3c/web-platform-tests/pull/4104#issuecomment-269660695 there are still some tests that need to be updated for this spec change I believe.
=> Spec update: stop decoding all %2es in paths

README.md, scripts/get-latest-platform-tests.js, src/url-state-machine.js
This matches https://github.com/whatwg/url/pull/196.
---
We shouldn't merge until the WPTs make it into master.
=> Spec update: disallow invalid IPv4 in the IPv6 parser

src/url-state-machine.js, test/to-upstream.json
Fixed bug in function `findLongestZeroSequence`, which has ignored trailing zeros sequences.
URL to test isssue:
`http://[1:0::]`
`url.host` in original version returns `[1:0:0:0:0:0:0:0]`, but must return: `[1::]`
=> Fix: not compressing trailing zeros in IPv6

lib/URL-impl.js, scripts/get-latest-platform-tests.js, src/url-state-machine.js
Follows https://github.com/whatwg/url/pull/213.
Waiting on tests in https://github.com/w3c/web-platform-tests/pull/4586 to get rebased.
=> Spec update: change path parsing for non-special URLs

README.md, lib/URL-impl.js, scripts/get-latest-platform-tests.js, src/url-state-machine.js
Follows https://github.com/whatwg/url/pull/224.
=> Spec update: cleanup API for file and non-special URLs

README.md, src/url-state-machine.js
Follows https://github.com/whatwg/url/pull/292.
=> Spec update: IPv4 in IPv6 cleanup

README.md, lib/URL-impl.js, lib/public-api.js, scripts/get-latest-platform-tests.js, src/url-state-machine.js
Follows https://github.com/whatwg/url/pull/311. This is both a spec update and a public API change.
=> Serialize origins as ASCII instead of Unicode

scripts/get-latest-platform-tests.js, test/web-platform.js
Follows https://github.com/w3c/web-platform-tests/pull/10955.
(Waiting on that PR to be merged, then update the commit hash, before merging this. This PR is mostly being put up as an example to the Node.js folks what they can do.)
=> Update tests for new way of testing bad base URLs

README.md, src/url-state-machine.js, test/file-url-origin.js
Closes #117.
I think for the purposes of our consumers this should be considered a breaking change.
=> Change file: URLs to have an opaque origin

package-lock.json, package.json, src/URL.webidl, src/URLSearchParams.webidl
Bumping [`webidl2js`](https://github.com/jsdom/webidl2js) from 12.0.0 to 14.0.0.
As a listed breaking change: 
> Removed support for [Constructor] in favor of supporting constructor operations, per [the Web IDL spec update](https://github.com/heycam/webidl/commit/91ca6ebb4d4fca9703309e19256bbc5f5dd77e3c).
=> Update Web IDLs

README.md, scripts/get-latest-platform-tests.js, src/url-state-machine.js
See https://github.com/whatwg/url/issues/440 and https://github.com/web-platform-tests/wpt/pull/23256.
=> Stop special casing U+0000 in parse fragment

scripts/get-latest-platform-tests.js, test/testharness.js
This adds urlsearchparams.any.js (not very new) and url-setters-stripping.any.js (new). It adds some special handling for urlsearchparams-constructor.any.js since https://github.com/web-platform-tests/wpt/commit/a2db8989c7e03901992c62c288b57e1ff752e241#diff-98a88afe60f6cbfccfe88b1d41bd951e added a FormData dependency.
Additionally, this adds code to clear out and re-create the directory of downloaded tests, since I was getting leftovers on my filesystem when experimenting with this and that was annoying. As a bonus, this means we can delete the .gitkeep files.
=> Roll web platform tests to latest

README.md, scripts/get-latest-platform-tests.js, src/url-state-machine.js
Follows https://github.com/whatwg/url/commit/cceb4356cca233b6dfdaabd888263157b2204e44.
=> Spec update: verify domain is not empty after Unicode ToASCII

README.md, src/url-state-machine.js
See https://github.com/whatwg/url/pull/512.
Note that if I didn't do `this.url.host = null;` or the subsequent line there were no test failures, so this warrants additional coverage.
=> Refactor file state

src/URL-impl.js, src/URLSearchParams-impl.js, src/encoding.js, src/infra.js, src/percent-encoding.js, src/url-state-machine.js, src/urlencoded.js
Follows https://github.com/whatwg/url/pull/518.
This generally tries to make the code correspond more explicitly to the specification in a few ways. It doesn't handle non-UTF-8 encodings yet, though.
Supersedes #152. /cc @annevk.
=> Spec update: make everything use percent-encode sets

README.md, scripts/get-latest-platform-tests.js, src/percent-encoding.js, src/urlencoded.js
This has no observable behavior changes and the component percent-encode set isn't even used by the rest of the implementation directly. However, it keeps us in sync with the spec, and it isn't totally dead code since it is used indirectly.
Also fixes various spec URLs in comments that were accidentally left pointing a PR preview in cf7a7c1c29f6853faf79f50c97e0767da2182a52.
=> Spec update: add the component percent-encode set

src/percent-encoding.js
This regressed in v8.2.0. Closes https://github.com/jsdom/data-urls/issues/17. Closes https://github.com/jsdom/data-urls/pull/18.
=> Fix percentDecode to return a Buffer instead of a Uint8Array

README.md, scripts/get-latest-platform-tests.js, src/url-state-machine.js
Implement the proposal for file URL path normalisation, as discussed in https://github.com/whatwg/url/issues/405
**(!!)** Please note that this pins the tests to a specific commit in my fork of the web platform tests. 
This should be updated if these changes are accepted, see https://github.com/web-platform-tests/wpt/pull/25716
=> Implement proposal for file URL path normalisation

README.md, src/url-state-machine.js
Follows https://github.com/whatwg/url/pull/558.
This also updates the documentation to make it clear that we have no encoding handling, and removes the mention of encodingOverride (which was ignored by the code).
=> Spec update: refactor query state

package-lock.json, package.json, src/URLSearchParams-impl.js
Reduce size of users dependency tree
Most of users already has lodash installed as its a dependency of thousands of packages
When i look at mine, I see 50 different versions of submodules,
This is also recommended action from lodash: https://lodash.com/per-method-packages and per method packages will no longer be available in v5
=> dep: reduce size of consumer node_modules

src/url-state-machine.js
It turns out that if we only need to convert a string into an array of code points, that's pretty easy.
=> Remove punycode dependency

live-viewer/index.html
=> Fix the live URL viewer in Safari

.gitignore, package-lock.json, package.json
Browserify is practically unmaintained and requires a lot of dependencies. Esbuild is a more modern alternative written in Go that is better on all those aspects.
=> Switch to esbuild for the live viewer

live-viewer/live-viewer.js
Discovered in https://github.com/whatwg/url/issues/677#issuecomment-993752115.
=> Live viewer: fix empty string URL inputs in shared links

package-lock.json, package.json, scripts/get-latest-platform-tests.js
Notably, we can remove the minipass-fetch dependency as new Node.js versions have fetch() built-in.
Closes #259.
=> Update dependencies and dev dependencies

package-lock.json, package.json, test/testharness.js, test/web-platform.js
Node.js v18+ has one built-in, which suffices for our purpose of running web platform tests.
=> Remove DOMException dev dependency

README.md, lib/URL-impl.js, lib/URL.webidl, scripts/get-latest-platform-tests.js, test/testharness.js
=> Implement URL.parse()

README.md, lib/url-state-machine.js
The spec's algorithm is based on ours, but the algorithm and variable names changed, so let's align.
Follows https://github.com/whatwg/url/commit/7ff8de0a1445abcabbbc4d33b292a5eddc8bd22d.
=> Match the spec's "find the IPv6 address compressed piece index"

eslint.config.mjs, lib/url-state-machine.js, package.json, scripts/benchmark.js
Due to a V8 bug (https://issues.chromium.org/issues/42204424), negative end-of-string matches are slow, as shown in #286. We can avoid triggering this slowdown for certain inputs by just implementing the trimming using loops.
Closes #286. Closes #288 by superseding it.
=> Implement faster trimming of control characters

lib/urlencoded.js
It appears we were trying to special-case _charset_ and File objects, but I can find no evidence that anywhere in this codebase, or the jsdom codebase, we ever need this support.
Part of #268.
=> Remove dead code in urlencoded serializer

README.md, lib/url-state-machine.js, package-lock.json, package.json, scripts/get-latest-platform-tests.js, test/web-platform.js
In addition to the dependency update on tr46, this includes a series of recent URL Standard changes:
* https://github.com/whatwg/url/commit/cd8f1d6c1ad0bab1cc8e40ad8ef6ee6626c57d57
* https://github.com/whatwg/url/commit/a6e4492001454d3d823108a4c48d77a6ad4eead5
* https://github.com/whatwg/url/commit/c3d173f3106e0e557a80e30e828edb369909e17b
* https://github.com/whatwg/url/commit/7f3e3b6866f8ef4d43562545c066e147a3f2a0b1
Closes https://github.com/jsdom/whatwg-url/issues/291.
----
Not actually mergeable yet because it doesn't include the new tr46 release, but that's coming very soon, just stuck behind a slower CI.
=> Update for Unicode 16 / TR46 rev 33
